package com.aichange.reviewer.builder;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for ChangeReportBuilder.
 */
class ChangeReportBuilderTest {

    private ChangeReportBuilder builder;

    @BeforeEach
    void setUp() {
        builder = new ChangeReportBuilder();
    }

    @Test
    void testBuildWithAllSections() {
        String report = builder
            .addHeader("user", "repo", "https://github.com/user/repo/pull/123", 5)
            .addFeatures("- New authentication system\n- Dark mode support")
            .addBugFixes("- Fixed memory leak\n- Fixed null pointer exception")
            .addImprovements("- Refactored database layer\n- Improved UI responsiveness")
            .addBusinessImpact("- 30% faster page load\n- Better user retention")
            .addRiskConsiderations("- Requires database migration\n- Breaking API changes")
            .addTestScenarios("- Test login flow\n- Test dark mode toggle")
            .build();

        assertNotNull(report);
        assertTrue(report.contains("# Change Report — user/repo"));
        assertTrue(report.contains("✨ Features"));
        assertTrue(report.contains("New authentication system"));
        assertTrue(report.contains("🐛 Bug Fixes"));
        assertTrue(report.contains("Fixed memory leak"));
        assertTrue(report.contains("⚡ Improvements"));
        assertTrue(report.contains("Refactored database layer"));
        assertTrue(report.contains("📊 Business Impact"));
        assertTrue(report.contains("30% faster page load"));
        assertTrue(report.contains("⚠️ Risk Considerations"));
        assertTrue(report.contains("Breaking API changes"));
        assertTrue(report.contains("🧪 Recommended Test Scenarios"));
        assertTrue(report.contains("Test login flow"));
        assertTrue(report.contains("Generated by AI Change Reviewer"));
    }

    @Test
    void testBuildWithoutOptionalSections() {
        String report = builder
            .addHeader("user", "repo", "https://github.com/user/repo/pull/456", 3)
            .build();

        assertNotNull(report);
        assertTrue(report.contains("# Change Report — user/repo"));
        assertTrue(report.contains("Commits analyzed: 3"));
        // All sections should have default "Nothing significant"
        assertTrue(report.contains("Nothing significant"));
    }

    @Test
    void testBuildWithEmptyStrings() {
        String report = builder
            .addHeader("user", "repo", "https://github.com/user/repo/pull/789", 1)
            .addFeatures("")
            .addBugFixes("   ")
            .build();

        assertNotNull(report);
        // Empty sections should use default
        assertTrue(report.contains("Nothing significant"));
    }

    @Test
    void testHeaderContainsCorrectInfo() {
        String report = builder
            .addHeader("aman0710", "ai-change-reviewer", "https://github.com/aman0710/ai-change-reviewer/pull/42", 10)
            .addFeatures("Test")
            .build();

        assertTrue(report.contains("aman0710/ai-change-reviewer"));
        assertTrue(report.contains("https://github.com/aman0710/ai-change-reviewer/pull/42"));
        assertTrue(report.contains("Commits analyzed: 10"));
    }

    @Test
    void testBuilderIsReusable() {
        builder.addHeader("user", "repo", "url", 1);
        builder.addFeatures("Feature 1");
        String report1 = builder.build();

        // Create new builder instance for second report
        ChangeReportBuilder builder2 = new ChangeReportBuilder();
        builder2.addHeader("user2", "repo2", "url2", 2);
        builder2.addFeatures("Feature 2");
        String report2 = builder2.build();

        assertTrue(report1.contains("user/repo"));
        assertTrue(report2.contains("user2/repo2"));
        assertNotEquals(report1, report2);
    }
}
