package com.aichange.reviewer.builder;

import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Builder for constructing markdown change reports.
 * Each section is independently addable; missing sections are filled with "Nothing significant".
 */
@Component
public class ChangeReportBuilder {

    private String header;
    private String features;
    private String bugFixes;
    private String improvements;
    private String businessImpact;
    private String riskConsiderations;
    private String testScenarios;

    public ChangeReportBuilder() {
        this.features = "Nothing significant";
        this.bugFixes = "Nothing significant";
        this.improvements = "Nothing significant";
        this.businessImpact = "Nothing significant";
        this.riskConsiderations = "Nothing significant";
        this.testScenarios = "Nothing significant";
    }

    public ChangeReportBuilder addHeader(String owner, String repo, String sourceUrl, int commitCount) {
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        this.header = String.format(
            "# Change Report — %s/%s\n" +
            "**Source:** %s\n" +
            "**Generated:** %s\n" +
            "**Commits analyzed:** %d\n" +
            "\n" +
            "---\n\n",
            owner, repo, sourceUrl, timestamp, commitCount
        );
        return this;
    }

    public ChangeReportBuilder addFeatures(String content) {
        if (content != null && !content.trim().isEmpty()) {
            this.features = content.trim();
        }
        return this;
    }

    public ChangeReportBuilder addBugFixes(String content) {
        if (content != null && !content.trim().isEmpty()) {
            this.bugFixes = content.trim();
        }
        return this;
    }

    public ChangeReportBuilder addImprovements(String content) {
        if (content != null && !content.trim().isEmpty()) {
            this.improvements = content.trim();
        }
        return this;
    }

    public ChangeReportBuilder addBusinessImpact(String content) {
        if (content != null && !content.trim().isEmpty()) {
            this.businessImpact = content.trim();
        }
        return this;
    }

    public ChangeReportBuilder addRiskConsiderations(String content) {
        if (content != null && !content.trim().isEmpty()) {
            this.riskConsiderations = content.trim();
        }
        return this;
    }

    public ChangeReportBuilder addTestScenarios(String content) {
        if (content != null && !content.trim().isEmpty()) {
            this.testScenarios = content.trim();
        }
        return this;
    }

    public String build() {
        return String.format(
            "%s" +
            "## ✨ Features\n\n%s\n\n" +
            "## 🐛 Bug Fixes\n\n%s\n\n" +
            "## ⚡ Improvements\n\n%s\n\n" +
            "## 📊 Business Impact\n\n%s\n\n" +
            "## ⚠️ Risk Considerations\n\n%s\n\n" +
            "## 🧪 Recommended Test Scenarios\n\n%s\n\n" +
            "---\n\n" +
            "*Generated by AI Change Reviewer*",
            header,
            features,
            bugFixes,
            improvements,
            businessImpact,
            riskConsiderations,
            testScenarios
        );
    }
}
